language: python
python:
  - "2.7"
env:
  global:
    - 'PIP_DOWNLOAD_CACHE=".pip_download_cache"'
    - 'WAD_FILES="package.json,Makefile,setup.py"'
    - 'WAD_INSTALL_COMMAND=ci/setup'
virtualenv:
  system_site_packages: true
services:
  - postgresql
before_script:
  - psql -c 'create database myapp_test;' -U postgres
before_install:
  # Use closer nameservers
  - printf "nameserver 199.91.168.70\nnameserver 199.91.168.71\n" | sudo tee /etc/resolv.conf

  # These need to be here and not in the env hash because they need to be
  # evaluated after the virtualenv has been setup
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - 'export WAD_ENVIRONMENT_VARIABLES="TRAVIS_PYTHON_VERSION,TRAVIS_NODE_VERSION,WAD_CACHE_PATH"'
  - 'export WAD_CACHE_PATH="node_modules,$PIP_DOWNLOAD_CACHE,$VIRTUAL_ENV"'
install:
  - time ci/wad
# OpenERP does not specify the version of pyparsing and the later
# version only work with py3k
  - pip install "pyparsing==1.5.7"
  - pip install distribute
#  - pip install flake8
#  - pip install nose
#  - pip install coveralls
  - ./install_nightly.sh
  - python setup.py install
script:
  - python setup.py test_on_travis
#  - nosetests --with-coverage --cover-package=sentry
#  - flake8 .
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing
notifications:
  email:
    - alainivars@gmail.com